export const GET_NASA_PICTURE_OF_THE_DAY = 'GET_NASA_PICTURE_OF_THE_DAY';
export const PUT_NASA_PICTURE_OF_THE_DAY = 'PUT_NASA_PICTURE_OF_THE_DAY';
export const PUT_NASA_PICTURE_OF_THE_DAY_ERROR = 'GET_NASA_PICTURE_OF_THE_DAY_ERROR';
export const PUT_NASA_PICTURE_OF_THE_DAY_LOADING = 'PUT_NASA_PICTURE_OF_THE_DAY_LOADING';
