export const GET_NASA_PICTURE_OF_THE_DAY = 'GET_NASA_PICTURE_OF_THE_DAY';
export const PUT_NASA_PICTURE_OF_THE_DAY = 'PUT_NASA_PICTURE_OF_THE_DAY';
export const GET_NASA_PICTURE_OF_THE_DAY_ERRORED = 'GET_NASA_PICTURE_OF_THE_DAY_ERROR';
